# Generated by Django 3.1 on 2022-01-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20220109_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
